In [1]:
import numpy as np
from sklearn.cluster import KMeans

In [2]:
# Adjacency matrix
A = np.array([
  [0, 1, 1, 0, 0, 1, 0, 0, 1, 1],
  [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
  [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
  [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
  [1, 0, 0, 1, 1, 0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
  [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
  [1, 0, 0, 0, 0, 0, 0, 0, 1, 0]])
A

array([[0, 1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [3]:
# Degree matrix
D = np.sum(A,axis=1)
np.diag(D)

array([[5, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2]])

In [4]:
# Laplace matrix
L = np.diag(D) - A
L

array([[ 5, -1, -1,  0,  0, -1,  0,  0, -1, -1],
       [-1,  2, -1,  0,  0,  0,  0,  0,  0,  0],
       [-1, -1,  2,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  2, -1, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  2, -1,  0,  0,  0,  0],
       [-1,  0,  0, -1, -1,  5, -1, -1,  0,  0],
       [ 0,  0,  0,  0,  0, -1,  2, -1,  0,  0],
       [ 0,  0,  0,  0,  0, -1, -1,  2,  0,  0],
       [-1,  0,  0,  0,  0,  0,  0,  0,  2, -1],
       [-1,  0,  0,  0,  0,  0,  0,  0, -1,  2]])

In [5]:
# Symmetric normalized Laplacian
sqrtD = np.diag(1.0 / (D ** (0.5)))
L_normalize = np.dot(np.dot(sqrtD, L), sqrtD)
L_normalize

array([[ 1.        , -0.31622777, -0.31622777,  0.        ,  0.        ,
        -0.2       ,  0.        ,  0.        , -0.31622777, -0.31622777],
       [-0.31622777,  1.        , -0.5       ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.31622777, -0.5       ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        , -0.5       ,
        -0.31622777,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.5       ,  1.        ,
        -0.31622777,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.2       ,  0.        ,  0.        , -0.31622777, -0.31622777,
         1.        , -0.31622777, -0.31622777,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -0.31622777,  1.        , -0.5       

In [6]:
# Eigendecomposition
eigValue,eigVector = np.linalg.eig(L)
dictEigval = dict(zip(eigValue,range(len(eigValue))))
# Select the eigenvector corresponding to the smallest 4 eigenvalues
kEig = np.sort(eigValue)[0:4]
index = [dictEigval[k] for k in kEig]
eigVector[:,index].astype('float16')

array([[ 0.3162 ,  0.234  ,  0.     , -0.     ],
       [ 0.3162 ,  0.3337 , -0.02039,  0.4907 ],
       [ 0.3162 ,  0.3337 , -0.02039,  0.4907 ],
       [ 0.3162 , -0.3337 , -0.4995 , -0.0962 ],
       [ 0.3162 , -0.3337 , -0.4995 , -0.0962 ],
       [ 0.3162 , -0.234  , -0.     ,  0.     ],
       [ 0.3162 , -0.3337 ,  0.4995 ,  0.0962 ],
       [ 0.3162 , -0.3337 ,  0.4995 ,  0.0962 ],
       [ 0.3162 ,  0.3337 ,  0.02039, -0.4907 ],
       [ 0.3162 ,  0.3337 ,  0.02039, -0.4907 ]], dtype=float16)

In [7]:
# Perform KMeans on the row vectors of the matrix of eigenvectors
kmeans = KMeans(n_clusters=4)
kmeans.fit(eigVector[:,index])
kmeans.labels_

array([3, 3, 3, 2, 2, 2, 1, 1, 0, 0])

In [8]:
vecs = eigVector[:,np.argsort(eigValue)].astype('float16')
vecs[:,1:4]

array([[ 0.234  ,  0.     , -0.     ],
       [ 0.3337 , -0.02039,  0.4907 ],
       [ 0.3337 , -0.02039,  0.4907 ],
       [-0.3337 , -0.4995 , -0.0962 ],
       [-0.3337 , -0.4995 , -0.0962 ],
       [-0.234  , -0.     ,  0.     ],
       [-0.3337 ,  0.4995 ,  0.0962 ],
       [-0.3337 ,  0.4995 ,  0.0962 ],
       [ 0.3337 ,  0.02039, -0.4907 ],
       [ 0.3337 ,  0.02039, -0.4907 ]], dtype=float16)